// <auto-generated />
namespace TrashCollecter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class thing22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thing22));
        
        string IMigrationMetadata.Id
        {
            get { return "201901092001594_thing22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
